import type { Case } from '../sim/types';

export const CASES: Case[] = [
  {
    id: 'case1',
    titleDa: 'Grundlæggende parametre',
    titleEn: 'Basic parameters',
    descriptionDa: 'Udforsk effekten af indblæsningstemperaturen på tørreresultatet.',
    descriptionEn: 'Explore the effect of inlet air temperature on drying outcome.',
    level: 'basic',
    startInputs: { T_main_in: 160 },
    goalsDa: [
      'Øg T_main_in fra 160°C til 200°C',
      'Observer ændring i udblæsningstemperatur',
      'Observer ændring i pulverfugt',
    ],
    goalsEn: [
      'Increase T_main_in from 160°C to 200°C',
      'Observe change in outlet temperature',
      'Observe change in powder moisture',
    ],
    facitHints: [
      'Højere indblæsningstemperatur → lavere pulverfugt',
      'T_out stiger ca. 0.5°C per 1°C stigning i T_main_in',
      'Energiforbruget øges proportionalt',
    ],
  },
  {
    id: 'case2',
    titleDa: 'Forårsvejr: Høj luftfugtighed',
    titleEn: 'Spring weather: High humidity',
    descriptionDa: 'Simuler drift ved høj omgivende luftfugtighed (forårsdag).',
    descriptionEn: 'Simulate operation at high ambient humidity (spring day).',
    level: 'basic',
    startInputs: { RH_amb: 80, T_amb: 15 },
    goalsDa: [
      'Startbetingelse: RH_amb = 80%, T_amb = 15°C',
      'Hold pulverfugt under 4%',
      'Juster parametre for at opretholde kvalitet',
    ],
    goalsEn: [
      'Starting condition: RH_amb = 80%, T_amb = 15°C',
      'Keep powder moisture below 4%',
      'Adjust parameters to maintain quality',
    ],
    facitHints: [
      'Øg T_main_in for at kompensere for øget luftfugtighed',
      'Reducer X_main_in ved at forvarme luften mere',
      'IFB temperatur kan sænkes lidt for at spare energi',
    ],
  },
  {
    id: 'case3',
    titleDa: 'Klæbrighed: Driftsgrænsen',
    titleEn: 'Stickiness: Operating limit',
    descriptionDa: 'Skub driftspunktet ind i den klæbrige zone og observer konsekvenserne.',
    descriptionEn: 'Push the operating point into the sticky zone and observe consequences.',
    level: 'advanced',
    startInputs: { T_main_in: 200, RH_amb: 85, m_feed: 10000 },
    goalsDa: [
      'Observer ΔT_sticky bliver positiv (klæbrig zone)',
      'Identificer hvilke parametre der hjælper mest',
      'Find en stabil drift med ΔT < -5°C',
    ],
    goalsEn: [
      'Observe ΔT_sticky becoming positive (sticky zone)',
      'Identify which parameters help most',
      'Find stable operation with ΔT < -5°C',
    ],
    facitHints: [
      'Sænk T_out ved at reducere T_main_in',
      'Øg IFB luftmængde for bedre efterkøling',
      'EFB med lav temperatur hjælper med at køle pulveret',
    ],
  },
  {
    id: 'case4',
    titleDa: 'Energioptimering',
    titleEn: 'Energy optimization',
    descriptionDa: 'Minimer energiforbruget per kg pulver uden at gå på kompromis med kvaliteten.',
    descriptionEn: 'Minimize energy consumption per kg powder without compromising quality.',
    level: 'advanced',
    startInputs: { T_main_in: 200, m_main_air: 120000 },
    goalsDa: [
      'Reducer E_per_kg_powder med mindst 10%',
      'Hold qualityIndex > 80',
      'Hold w_p < 4%',
    ],
    goalsEn: [
      'Reduce E_per_kg_powder by at least 10%',
      'Keep qualityIndex > 80',
      'Keep w_p < 4%',
    ],
    facitHints: [
      'Reducer T_main_in til minimum acceptabelt niveau',
      'Reducer m_main_air til minimumsgrænsen',
      'Optimer forholdet mellem hoved- og fluidbedluft',
    ],
  },
  {
    id: 'case5',
    titleDa: 'Fejlfinding: Høj fugt i pulver',
    titleEn: 'Troubleshooting: High powder moisture',
    descriptionDa: 'Produktionsprøver viser 6% fugt i pulveret. Find og løs problemet.',
    descriptionEn: 'Production samples show 6% moisture in powder. Find and solve the problem.',
    level: 'advanced',
    startInputs: { T_main_in: 165, m_feed: 9500, x_ds: 0.48 },
    goalsDa: [
      'Diagnosticer årsagen til høj pulverfugt',
      'Bring w_p tilbage under 4%',
      'Dokumenter hvilke parametre der var årsagen',
    ],
    goalsEn: [
      'Diagnose the cause of high powder moisture',
      'Bring w_p back below 4%',
      'Document which parameters were the cause',
    ],
    facitHints: [
      'Lav tørstofkoncentration i fødegods øger vandmængden',
      'Lav indblæsningstemperatur giver utilstrækkelig tørring',
      'Løsning: øg T_main_in og kontroller koncentreringsprocessen',
    ],
  },
  {
    id: 'case6',
    titleDa: 'Manuel styring: Fejl på automatik',
    titleEn: 'Manual control: Automation failure',
    descriptionDa: 'Automatstyringen af hovedluften er ude af drift. Styr anlægget manuelt via fluid beds.',
    descriptionEn: 'Main air automatic control is down. Control the plant manually via fluid beds.',
    level: 'pro',
    startInputs: { T_main_in: 175, m_main_air: 100000 },
    goalsDa: [
      'Fastlås T_main_in og m_main_air',
      'Brug kun IFB og EFB til regulering',
      'Oprethold w_p 3-4% og T_product < T_sticky - 10°C',
    ],
    goalsEn: [
      'Lock T_main_in and m_main_air',
      'Use only IFB and EFB for control',
      'Maintain w_p 3-4% and T_product < T_sticky - 10°C',
    ],
    facitHints: [
      'IFB med lav fugtighed tørrer pulveret yderligere',
      'EFB køler og kan justere slutfugtighed',
      'Reduktion af produktionshastighed kan være nødvendig',
    ],
  },
  {
    id: 'case7',
    titleDa: 'Lav udblæsningstemperatur',
    titleEn: 'Low outlet temperature',
    descriptionDa: 'Hvad er den lavest mulige udblæsningstemperatur uden kvalitetsforringelse?',
    descriptionEn: 'What is the lowest possible outlet temperature without quality degradation?',
    level: 'pro',
    startInputs: { T_main_in: 180 },
    goalsDa: [
      'Reducer T_out gradvist ved at sænke T_main_in',
      'Find grænsen hvor ΔT_sticky = 0',
      'Beregn energibesparelse vs. risiko',
    ],
    goalsEn: [
      'Gradually reduce T_out by lowering T_main_in',
      'Find the limit where ΔT_sticky = 0',
      'Calculate energy savings vs. risk',
    ],
    facitHints: [
      'T_out minimum bestemmes af klæbrighedskurven',
      'Sikkerhedsmargin på mindst 10°C anbefales',
      'Lavere T_out kræver tørrere luft (lavere X_in)',
    ],
  },
];
